name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC Build Tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: .\build.bat
      - name: Package
        run: Compress-Archive *.exe createprocess.zip
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            *.zip
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Release
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Release notes
        run: |
          echo "sha256 $(sha256sum artifacts/*.zip | awk '{print $1}')" >release-notes.md
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          bodyFile: release-notes.md
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: artifacts/*.zip
